In [1]:
import numpy as np
import math

# 1次元配列

In [2]:
# 1次元配列を作成
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
# 数字が連続した配列の場合はnp.arange()を使って作成することもできる
np.arange(5)

array([0, 1, 2, 3, 4])

# 多次元配列

In [4]:
# 多次元配列を作成
np.array([[1, 2, 3],
          [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

# 特殊な配列

In [5]:
# 要素数がすべて0の配列はnp.zeros()関数を使って作成できる
np.zeros([2, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# 要素数がすべて1の配列はnp.ones()関数を使って作成できる
np.ones([2, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 配列の計算

## 1. 四則演算
pythonでは本来、list型とint型の演算は型が違うためできない。  
しかし、NumPyを使えば配列内の全ての要素に対して演算を行うことができる。  
この機能を **ブロードキャスト** と呼ぶ。  


In [7]:
# 足し算
np.array([1, 2, 3]) + 2

array([3, 4, 5])

In [8]:
# 掛け算
np.array([1, 2, 3]) * 3

array([3, 6, 9])

In [9]:
# 割り算
np.array([1, 2, 3]) / 7

array([0.14285714, 0.28571429, 0.42857143])

## 2. 配列の合計

In [10]:
a = np.array([1, 2, 3, 4])
a.sum()

10

## 3. 配列の内積

In [11]:
b = np.array([1, 2])
c = np.array([2, 3])
np.dot(b, c)

8

これはb[0]とc[0]の積と、b[1]とc[1]の積の和を取っている。  
数字で説明すると、1 × 2 + 2 × 3 = 8という計算を行なっている。  
行列の内積は線形代数と呼ばれる分野で登場。  

※　内積は要素数が一致していれば計算できるため、要素数の違う配列同士を計算しようすると次のようなエラーが起こる。

In [13]:
d = np.array([1, 3, 5])
e = np.array([2, 4])
np.dot(d, e)

ValueError: shapes (3,) and (2,) not aligned: 3 (dim 0) != 2 (dim 0)

## 4. 平方根の計算

In [14]:
np.sqrt(9)

3.0

# 乱数の生成

乱数の生成はPythonのrandomモジュールでも計算できますが、NumPyを使っても乱数を生成することができる  
NumPyを使う利点としては、乱数の配列が簡単に作成できることと、配列の処理が高速  

In [15]:
# 0〜1の乱数を1つ生成
r = np.random.rand(3)
r

array([0.84757417, 0.28868924, 0.44463158])

In [16]:
type(r)

numpy.ndarray

In [17]:
# 乱数を複数生成するとNumPy配列で与えられるため、次のようにすることで要素が0~1の行列を生成することもできる
np.random.rand(2, 2)

array([[0.60824703, 0.75529495],
       [0.89551994, 0.19368186]])

In [18]:
# 整数の乱数を「1個」生成
# 引数に整数を与えることで、その数字未満の乱数が「1個」生成される。
np.random.randint(100)

76

# 問題１：多次元配列を作成しよう

次のような出力になるように、NumPyを使って多次元配列を作成してみましょう。  
  
[[11 12 13]  
 [21 22 23]  
 [31 32 33]]

In [19]:
# 配列を作成してください。
a = np.array([[11, 12, 13],
            [21, 22, 23],
            [31, 32, 33]])
          
# 作成した配列を出力してください。
print(a)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


# 問題２：NumPy配列内の要素を3倍をしよう

次のNumPy配列があります。  
  
  [[1 2 3]  
 [4 5 6]]  
 
 この配列が次のようになるようにブロードキャストの機能を使って計算してみましょう。  
   
   [[ 3  6  9]  
 [12 15 18]]  
 

In [20]:
# ブロードキャストを使ってNumpy配列内の要素を3倍してください。

# 次の配列があります。
a = np.array([[1, 2, 3],
             [4, 5, 6]])

# ブロードキャストを使って上の配列内の要素を3倍にしてください。
a_triple = a * 3

# 3倍にした配列を出力してください。
print(a_triple)

[[ 3  6  9]
 [12 15 18]]


# 問題３：NumPy配列の要素の合計を求めよう

次のNumPy配列があります。  
  
[[1 1 2]  
 [3 5 8]]
   
   この配列の要素の合計を計算し、計算結果を出力してください。

In [21]:
# 配列の要素の合計を求めてください。

# 次の配列があります。
a = np.array([[1, 1, 2],
             [3, 5, 8]])

# 配列の要素の合計を計算してください。
a_sum = a.sum()

# 計算した値を出力してください。
print(a_sum)

20


# 問題4： cos類似度の計算

In [22]:
# cos類似度を計算してください
# 次の2つのベクトルがあります。
a = np.array([2, 1])
b = np.array([1, 3])

In [23]:
# まずは分子を計算します。
# 2つのベクトルの内積を計算してください。
InnerProduct = np.dot(a, b)
InnerProduct

5

In [24]:
# 次に分母を計算します。
# まずはベクトルaの絶対値を計算します。
# ベクトルaの要素を2乗してください。
a_square = np.square(a)
print(a_square)

[4 1]


In [25]:
# 要素が2乗されたベクトルaの要素の和を求めてください。
a_square_sum = a_square.sum()
a_square_sum

5

In [26]:
# 上で得られた値の平方根をとり、ベクトルaの絶対値を得ます。
a_AbsoluteＶalue = np.sqrt(a_square_sum)
a_AbsoluteＶalue

2.23606797749979

In [27]:
# 同様の操作をベクトルbについても行います。
# まずはベクトルbの絶対値を計算します。
# ベクトルbの要素を2乗してください。
b_square = np.square(b)

In [28]:
# 要素が2乗されたベクトルbの要素の和を求めてください。
b_square_sum = b_square.sum()

In [29]:
# 上で得られた値の平方根をとり、ベクトルbの絶対値を得ます。
b_AbsoluteＶalue = np.sqrt(b_square_sum)
b_AbsoluteＶalue

3.1622776601683795

In [30]:
# 2つのベクトルの絶対値の積を求めて、分母の計算が終わります。
ab_sum_AbsoluteＶalue = a_AbsoluteＶalue * b_AbsoluteＶalue
ab_sum_AbsoluteＶalue

7.071067811865476

In [31]:
# 分子を分母で割ってcos類似度を求めてください。
ab_cos = InnerProduct / ab_sum_AbsoluteＶalue
ab_cos

0.7071067811865475

In [32]:
# 少数第三位を四捨五入してください。
round(ab_cos, 2)

0.71

In [33]:
# 計算したcos類似度を出力してください。
print(round(ab_cos, 2))

0.71


## 四捨五入：round (   )

## $round  ( number [　　, ndigits] )$

引数はそれぞれ、  

第一引数number : 四捨五入したい値  
第二引数ndigits : 四捨五入後の小数点の桁数  
尚、第二引数ndigitsに何も設定しない場合は、その数値に最も近い整数値を返す。  

In [34]:
# 第二引数を省略した場合は、最も近い整数値となる
print("第二引数を省略した場合(最も近い整数値となる): ", round(ab_cos))


# 小数点以下1桁　（小数点第二位を四捨五入）
print("小数点第二位を四捨五入: ", round(ab_cos, 1))

# 小数点以下2桁　（小数点第三位を四捨五入）
print("小数点第三位を四捨五入: ", round(ab_cos, 2))


# 小数点以下3桁　（小数点第四位を四捨五入）
print("小数点第四位を四捨五入: ", round(ab_cos, 3))

# 第二引数ndigitsに負の整数を設定すると整数部分が四捨五入される。
print("整数部分を四捨五入: ", round(ab_cos, -1))


第二引数を省略した場合(最も近い整数値となる):  1.0
小数点第二位を四捨五入:  0.7
小数点第三位を四捨五入:  0.71
小数点第四位を四捨五入:  0.707
整数部分を四捨五入:  0.0


## 四捨五入：format()
## $ format (x , 書式 ) $

標準関数format()の書式設定を使う  
例えば小数点第3位を四捨五入して、小数2位まで表示するには、$ .2f $ と指定  

In [35]:
# 円周率を例にします。
Pi = 3.141592653589793
print("円周率: " , str(a))



# 整数値　（小数点第一位を四捨五入）
print("円周率の整数値: " , format(Pi, '.0f'))

# 小数点以下1桁　（小数点第二位を四捨五入）
print("円周率の小数点以下1桁: " , format(Pi, '.1f'))

# 小数点以下2桁　（小数点第三位を四捨五入）
print("円周率の小数点以下2桁: " , format(Pi, '.2f'))


# 小数点以下3桁　（小数点第四位を四捨五入）
print("円周率の小数点以下3桁: " , format(Pi, '.3f'))

# 小数点以下5桁　（小数点第六位を四捨五入）
print("円周率の小数点以下5桁: " , format(Pi, '.5f'))

円周率:  [2 1]
円周率の整数値:  3
円周率の小数点以下1桁:  3.1
円周率の小数点以下2桁:  3.14
円周率の小数点以下3桁:  3.142
円周率の小数点以下5桁:  3.14159


# cos_sim関数

In [57]:
# cos_sim関数を作成
def cos_sim(v1, v2):
    return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

In [58]:
print(cos_sim(a, b))

0.7071067811865475


In [59]:
# 小数点以下2桁　（小数点第三位を四捨五入）
print("aとbのcos類似度: ", cos_sim(a, b))

# 小数点以下2桁　（小数点第三位を四捨五入）
print("小数点第三位を四捨五入: ", round(cos_sim(a, b), 2))

aとbのcos類似度:  0.7071067811865475
小数点第三位を四捨五入:  0.71
